import {notFound} from 'next/navigation';
import {projects,categories} from '../../../content/projects';
import ProjectVisual from '../../../components/ProjectVisual';
import ProjectCard,{Tags} from '../../../components/ProjectCard';
import {pageMetadata} from '../../../lib/metadata';
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);return p?pageMetadata(p.title,p.summary,`/projects/${slug}/`,p.media==='car'?'/images/drawing-car.jpg':undefined):{title:'Not found'}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const project=projects.find(p=>p.slug===slug);if(!project)notFound();const category=categories.find(c=>c.slug===project.categories[0])!;
 const related=projects.filter(p=>p.slug!==slug&&p.categories.some(c=>project.categories.includes(c))).slice(0,2);
 return <main id="main" className="wrap"><div className="page-intro project-intro"><nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href={`/work/${category.slug}/`}>{category.title}</a><span>/</span><span>{project.shortTitle}</span></nav><p className="eyebrow">{project.context}{project.dates?` · ${project.dates}`:''}</p><h1>{project.title}</h1><p className="lead">{project.summary}</p><Tags tags={project.technologies}/></div><dl className="project-facts"><div><dt>My role</dt><dd>{project.role}</dd></div><div><dt>Platform</dt><dd>{project.platform}</dd></div><div><dt>Project context</dt><dd>{project.status}</dd></div></dl><figure className="project-hero"><ProjectVisual kind={project.media} priority/><figcaption>{project.caption}{project.media==='car'&&<> <a href={project.links[0].url}>Source report ↗</a></>}</figcaption></figure><div className="project-body"><aside><nav aria-label="On this page"><p className="eyebrow">In this project</p>{project.sections.map((s,i)=><a href={`#${s.id}`} key={s.id}><span>{String(i+1).padStart(2,'0')}</span>{s.title}</a>)}{project.links.length>0&&<a href="#resources"><span>↗</span>Report & demonstration</a>}</nav></aside><div className="prose">{project.sections.map(s=><section id={s.id} key={s.id}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}{s.code&&<pre><code>{s.code}</code></pre>}</section>)}{project.links.length>0&&<section id="resources"><h2>Report & demonstration</h2><p>The team report contains the full design discussion and references. The video opens on YouTube only when selected.</p><div className="resource-links">{project.links.map(l=><a className="text-link" href={l.url} key={l.url}>{l.label} ↗</a>)}</div></section>}</div></div>{related.length>0&&<section className="section"><div className="section-heading"><p className="eyebrow">Keep exploring</p><h2>Related work.</h2></div><div className="card-grid">{related.map(p=><ProjectCard key={p.slug} project={p}/>)}</div></section>}</main>
}
