import type {Project} from './types';
export type {Project, Section} from './types';
import {drawingCarPhoto,floatingBoxReportUrl,floatingBoxSystem,floatingBoxWiring} from './media';
import {gimbalBoardComparison,gimbalVideos} from './gimbal';
export const reportUrl = 'https://ece4760.github.io/Projects/Fall2025/sjz44_glk49_rcw253/final_report.html';
export const projects: Project[] = [
  {
    slug:'autonomous-drawing-car',title:'Autonomous Drawing Car',shortTitle:'Autonomous Drawing Car',
    summary:'Two Pico W controllers turn mouse-drawn waypoints into robot motion, with a VGA interface, UDP communication, and IMU heading feedback.',
    categories:['robotics-embedded'],featured:true,role:'BNO055 driver adaptation and integration; shared hardware and software development',dates:'Fall 2025',context:'Cornell ECE 4760 · Team of three',platform:'Two Raspberry Pi Pico W controllers',status:'Built and demonstrated',technologies:['C / Pico SDK','UDP','Protothreads','IMU feedback'],cover:drawingCarPhoto,caption:'Drawing car by Gebran Kastoun, Ruby Wu, and Sarah Zhong. Photo from the team report.',results:['Mouse input, wireless waypoints, and physical motion integrated in a demonstrated system.'],links:[{label:'Read the full team report',url:reportUrl},{label:'Watch the demonstration on YouTube',url:'https://www.youtube.com/watch?v=8FTqkum7d4I'}],
    sections:[
      {id:'problem',title:'Overview',paragraphs:['The project connects a mouse and VGA interface to a mobile robot. Waypoints captured by the interface-side Pico W are sent over UDP to the car-side Pico W, where a state machine coordinates heading alignment and forward motion.','The core constraint is concurrent operation: user input, display rendering, wireless traffic, sensor reads, and motor control all share a small embedded platform.']},
      {id:'contribution',title:'My contribution',paragraphs:['I adapted the JRDPropulsion BNO055 library from C++ to C and integrated it with the Pico SDK for heading estimation. Ruby Wu led the chassis and marker-holder CAD work; Sarah Zhong led the UDP communication implementation. We collaborated on software, electrical setup, and mechanical integration.','We built on Cornell course examples from Bruce Land and Van Hunter Adams for VGA graphics, USB input, PWM, networking, and Protothreads.']},
      {id:'architecture',title:'Design',paragraphs:['The interface controller handles mouse input, waypoint storage, route planning, and wireless transmission, with a dedicated core for rendering. The robot receives waypoints, reads BNO055 heading over I²C, and actuates its motors through PWM.','Semaphore signaling defers payload processing from receive callbacks to cooperative Protothreads.'],bullets:['Interface: mouse → waypoint list → optional route ordering → UDP.','Robot: UDP → navigation state machine → PWM motor control.','Feedback: the BNO055 measures heading; traveled distance is estimated from time.']},
      {id:'decisions',title:'Key decisions',paragraphs:['Direct-follow mode preserves the input order. Optimized-route mode reorders the waypoint set using nearest-neighbor planning followed by 2-opt refinement. The latter targets a shorter route through the points; it does not preserve the original drawing’s stroke order or guarantee a globally shortest path.','Optimization is deferred until transmission and its result is cached. Adding waypoints invalidates the cached route. This keeps route computation out of the routine input/rendering path.','The robot uses heading feedback but has no wheel encoders. Forward travel duration is estimated from distance and expected speed, so orientation sensing does not provide closed-loop position control.']},
      {id:'validation',title:'Testing and results',paragraphs:['The integrated system was built and demonstrated. During drawing, marker friction interfered with timed travel and increased drift.','Surface conditions, wheel slip, and marker drag can change actual travel without being detected by the timing-based distance estimate.']},
      {id:'improvements',title:'Limitations and next steps',paragraphs:['Next steps would be to improve the marker mount and add distance feedback. Repeatable paths and position measurements would help compare drawing accuracy across surfaces and marker conditions.']},
    ]
  },
  {
    slug:'floating-box',title:'Floating Box',shortTitle:'Floating Box',
    summary:'A motorized spool keeps a suspended box near a set height as its support moves, using distance feedback and PID control.',
    categories:['robotics-embedded'],featured:false,role:'Servo PWM driver and hardware integration; joint testing and debugging',dates:'Spring 2026',context:'Cornell ECE 3140 · Team of two',platform:'FRDM-KL46Z · time-of-flight sensor · continuous servo',status:'Built and demonstrated',technologies:['PID control','PWM','I²C','Time-of-flight sensing'],cover:floatingBoxSystem,caption:floatingBoxSystem.caption,featuredVideo:{provider:'youtube',videoId:'vz4-YAJWREw',title:'Floating Box project demonstration',caption:'The box adjusts its suspension to stay near a set height as the support moves.'},gallery:[floatingBoxWiring],results:['The integrated system maintained the box near its target height while the support moved vertically.'],links:[{label:'Read the team project page',url:floatingBoxReportUrl}],sections:[
      {id:'problem',title:'Overview',paragraphs:['A box hangs from a string attached to a motorized spool. As the support moves up or down, the spool changes the string length to keep the box at roughly the same height above the ground.','A time-of-flight sensor on the bottom of the box measures its distance from the ground. The FRDM-KL46Z board reads that feedback and commands a continuous servo through PWM.']},
      {id:'contribution',title:'My contribution',paragraphs:['I led development of the servo driver and handled the hardware integration. Sienna developed the time-of-flight sensor driver and organized the code structure. We worked together on system integration and debugging, including the PWM timing issue that appeared during full-system testing.']},
      {id:'architecture',title:'Control and hardware',paragraphs:['The controller filters sensor measurements, compares the measured height with a setpoint, and adjusts the servo speed and direction through PWM. The servo winds or unwinds the string to counter movement of the support.','The sensor connects over I²C. Its approximately three-foot range limits the distance over which the system can correct, and the servo’s maximum turn rate limits how quickly it can respond.']},
      {id:'debugging',title:'Testing and debugging',paragraphs:['After testing the sensor and servo drivers separately, we integrated the system. The box corrected well in one direction but poorly in the other. We isolated the problem by bypassing the PID controller and then the normalization logic; the asymmetry remained under direct PWM commands.','Oscilloscope measurements showed a pulse-width offset below 1000 microseconds. We traced that offset to incorrect scaling of the board clock in the PWM timing code. Correcting the scaling restored the servo response in both directions.']},
      {id:'result',title:'Result',paragraphs:['The final demonstration shows the box staying at roughly a constant height while its support moves vertically. The original team page includes the video and further implementation details.']},
    ]
  },
  {
    slug:'gimbal-controller',title:'CUAir Gimbal Controller',shortTitle:'Gimbal Controller',summary:'A custom stabilization board connecting IMU sensing, C++ control firmware, servo actuation, and ground-station telemetry.',categories:['power-electronics','robotics-embedded'],featured:true,role:'Custom PCB, firmware, board bring-up, and integration',context:'Cornell CUAir',platform:'ATmega328P · Raspberry Pi telemetry bridge',status:'Board bring-up and integration',technologies:['Custom PCB','C++','PID control','I²C / UART'],media:'gimbal',caption:'System architecture (illustrative).',boardComparison:gimbalBoardComparison,gallery:gimbalVideos,links:[],sections:[
      {id:'problem',title:'Overview',paragraphs:['A gimbal controller links an orientation sensor to servo motion while exposing enough information to understand the system during integration. The work spans the custom electronics, embedded control loop, telemetry path, and physical interfaces.','This CUAir design uses an ATmega328P with an IMU, servo connections, UART, and programming and debug interfaces on a custom PCB.']},
      {id:'contribution',title:'My contribution',paragraphs:['My work covered the custom stabilization PCB, C++ firmware, and board bring-up, including power and interface debugging.','The controller is part of the CUAir system. Its electronics and firmware connect to servo hardware and the team’s ground-station telemetry path.']},
      {id:'architecture',title:'Design',paragraphs:['IMU feedback reaches the ATmega328P over I²C. PID control in the firmware produces PWM servo commands. Angle telemetry leaves over UART and passes through a Raspberry Pi to the ground station.','The local feedback loop drives the gimbal; telemetry exposes its reported angles during integration.']},
      {id:'decisions',title:'Key decisions',paragraphs:['The PCB includes test points and status LEDs alongside programming and debug interfaces. This gives bring-up work physical access to power and signals instead of relying only on the final mechanical behavior.','UART telemetry carries angle information into the wider aircraft system during integration.']}
    ]
  },
  {
    slug:'tinyrv2-processor',title:'TinyRV2 Five-Stage Pipelined Processor',shortTitle:'TinyRV2 Processor',summary:'A 27-instruction RISC-V subset in Verilog, explored through stalling and fully bypassed pipelines with latency-aware memory interfaces.',categories:['digital-design'],featured:false,role:'RTL implementation and processor verification',context:'Course processor-design project',platform:'Verilog · Python / pytest',status:'RTL implementation and simulation testing',technologies:['Verilog','RISC-V','Forwarding','pytest'],media:'pipeline',caption:'Illustrative pipeline diagram.',links:[],sections:[
      {id:'problem',title:'Overview',paragraphs:['A pipeline overlaps instructions, but that overlap introduces dependencies: an instruction may need a result that has not yet been written back, a load may still be waiting for memory, and a branch may invalidate younger work.','The project implements a 27-instruction TinyRV2 RISC-V subset in Verilog, with stalling and fully bypassed five-stage variants. The design includes a variable-latency integer multiplier and valid/ready memory interfaces.']},
      {id:'contribution',title:'My contribution',paragraphs:['My work covered datapath and control implementation, forwarding, interlocks, branch squashing, and verification using assembly tests and cycle-level traces within the course infrastructure.']},
      {id:'architecture',title:'Design',paragraphs:['Fetch, decode, execute, memory, and writeback form the pipeline. Forwarding paths supply results from execute, memory, and writeback when they are available, reducing the need to wait for a register-file write.','A load-use dependency needs a stall when the requested value is not yet available. Branch squashing removes younger instructions on a redirected path.']},
      {id:'decisions',title:'Key decisions',paragraphs:['The stalling and bypassed variants expose two ways to preserve data dependencies. Forwarding needs source selection and dependency checks; stalling holds work until its inputs are available.','Valid/ready instruction and data memory interfaces make backpressure part of the control problem. A request or result cannot be treated as completed simply because a clock cycle has passed. The variable-latency multiplier introduces a similar need to account for completion.'],code:'// Illustrative load-use dependency\nlw  x1, 0(x2)\nadd x3, x1, x4\n\n// The add must wait until the loaded x1 is available.'},
      {id:'validation',title:'Testing and results',paragraphs:['The verification approach uses directed and randomized assembly tests through Python/pytest, comparisons against a functional ISA model, and cycle-level traces. Functional comparison checks instruction-visible behavior; traces help explain where stalls, forwarding, and squashes occur.']},
      {id:'tinyrv1',title:'TinyRV1 FPGA companion',paragraphs:['TinyRV1 is a separate eight-instruction, single-cycle processor, with a Verilog datapath and control and directed trace-based verification. This companion implementation was synthesized and deployed on an Intel Cyclone V FPGA.','TinyRV1 is the FPGA implementation; TinyRV2 is the separate five-stage RTL and simulation project.']}
    ]
  },
  {
    slug:'avionics-power-converter',title:'12S → 24 V Avionics Power Converter',shortTitle:'Avionics Power Converter',summary:'A synchronous buck-converter design intended to power avionics from the primary flight battery, with protection, current sensing, and DroneCAN telemetry.',categories:['power-electronics'],featured:false,role:'Power-converter design and PCB layout',context:'Cornell CUAir avionics',platform:'Altium · DroneCAN · Pixhawk',status:'Converter design',technologies:['Altium','Synchronous buck','Current sensing','DroneCAN'],media:'power',caption:'Intended power and telemetry architecture.',links:[],sections:[
      {id:'problem',title:'Overview',paragraphs:['The design targets a 24 V avionics rail from a 12S primary flight battery, with the goal of removing a separate 6S avionics battery.','Power conversion is only one part of the system: protection, filtering, sensing, and telemetry connect the electrical supply to the aircraft’s avionics architecture.']},
      {id:'contribution',title:'My contribution',paragraphs:['The project covers synchronous buck-converter design and PCB layout in Altium, with transient protection, input filtering, input/output current sensing, and DroneCAN telemetry toward the Pixhawk and ground station.']},
      {id:'architecture',title:'Design',paragraphs:['The power path runs from the primary battery through protection and filtering into the synchronous buck stage, then to the intended 24 V avionics load. Current sensing at the input and output provides visibility into the power path.','The telemetry design uses DroneCAN to send information to the Pixhawk and ground station.']},
      {id:'decisions',title:'Key decisions',paragraphs:['A synchronous buck topology provides the step-down conversion between the primary battery and the avionics rail. Input filtering and transient protection address the supply interface, while current sensing and DroneCAN address system visibility.']}
    ]
  },
  {
    slug:'galton-board',title:'Real-Time Galton Board',shortTitle:'Real-Time Galton Board',summary:'An RP2040 particle simulation that brings together fixed-point physics, multicore processing, and a PIO/DMA-driven VGA output path.',categories:['robotics-embedded'],featured:false,role:'Embedded C implementation and performance optimization',context:'Microcontroller simulation project',platform:'RP2040 · VGA',status:'Embedded implementation',technologies:['C','Fixed-point math','Multicore','PIO / DMA'],media:'galton',caption:'Compute and display architecture (illustrative).',links:[],sections:[
      {id:'problem',title:'Overview',paragraphs:['A Galton board simulation repeatedly updates moving particles and their collisions while producing a visible output. As the particle population grows, physics work competes with the constraints of a real-time display.','This RP2040 C implementation explores that boundary through multicore physics processing, fixed-point arithmetic, a distance approximation, and processor overclocking. VGA output uses PIO and DMA.']},
      {id:'contribution',title:'My contribution',paragraphs:['The work spans the embedded C simulation and its performance-oriented implementation: distributing physics work across cores, using fixed-point arithmetic, and applying the alpha-max-beta-min distance approximation. The display path uses the RP2040’s PIO and DMA peripherals.']},
      {id:'architecture',title:'Design',paragraphs:['Physics processing updates particle state, while the VGA path uses PIO and DMA for display output. Moving signal-generation work into peripherals changes how much CPU time is available for simulation.','Display refresh and physics update rate are separate constraints: generating the VGA signal and updating every particle involve different work.']},
      {id:'decisions',title:'Key decisions',paragraphs:['Fixed-point arithmetic changes the representation and cost of physics calculations. Alpha-max-beta-min approximates a distance using the larger and smaller absolute coordinate differences, avoiding an exact square root in that operation.','Multicore processing distributes physics work. Overclocking was also part of the optimization, alongside the software changes.']}
    ]
  }
];
export const categories = [
 {slug:'power-electronics',title:'Power & Electronics',description:'Power conversion, custom boards, and avionics integration.',featured:'avionics-power-converter',diagram:'power'},
 {slug:'robotics-embedded',title:'Robotics & Embedded',description:'Sensing, control, and concurrent software on embedded hardware.',featured:'autonomous-drawing-car',diagram:'gimbal'},
 {slug:'digital-design',title:'Digital Design',description:'Processor datapaths, pipeline control, verification, and FPGA implementation.',featured:'tinyrv2-processor',diagram:'pipeline'},
];
export function getProject(slug:string){return projects.find(p=>p.slug===slug)!}
