export type Section = { id: string; title: string; paragraphs: string[]; bullets?: string[]; code?: string };
export type Project = {
  slug: string; title: string; shortTitle: string; summary: string; categories: string[];
  featured: boolean; role: string; dates?: string; context: string; platform: string; status: string;
  technologies: string[]; media: 'car'|'gimbal'|'pipeline'|'power'|'galton'; caption: string;
  results?: string[]; links: {label:string;url:string}[]; sections: Section[];
};
export const reportUrl = 'https://ece4760.github.io/Projects/Fall2025/sjz44_glk49_rcw253/final_report.html';
export const projects: Project[] = [
  {
    slug:'autonomous-drawing-car',title:'Autonomous Drawing Car',shortTitle:'Autonomous Drawing Car',
    summary:'From a mouse-drawn path to physical motion. Two Pico W controllers connect a VGA drawing interface to an IMU-guided robot over UDP.',
    categories:['robotics-embedded'],featured:true,role:'BNO055 driver adaptation and integration; shared hardware and software development',dates:'Fall 2025',context:'Cornell ECE 4760 · Team of three',platform:'Two Raspberry Pi Pico W controllers',status:'Built and demonstrated',technologies:['C / Pico SDK','UDP','Protothreads','IMU feedback'],media:'car',caption:'The team’s drawing car. Photograph from the public ECE 4760 report by Gebran Kastoun, Ruby Wu, and Sarah Zhong.',results:['Mouse input, wireless waypoints, and physical motion integrated in a demonstrated system.'],links:[{label:'Read the full team report',url:reportUrl},{label:'Watch the demonstration on YouTube',url:'https://www.youtube.com/watch?v=8FTqkum7d4I'}],
    sections:[
      {id:'problem',title:'A drawing interface with a physical output',paragraphs:['The project connects a mouse and VGA interface to a mobile robot. Waypoints captured by the interface-side Pico W are sent over UDP to the car-side Pico W, where a state machine coordinates heading alignment and forward motion.','The core constraint is concurrent operation: user input, display rendering, wireless traffic, sensor reads, and motor control all share a small embedded platform.']},
      {id:'contribution',title:'My contribution, within a team effort',paragraphs:['I adapted the JRDPropulsion BNO055 library from C++ to C and integrated it with the Pico SDK for heading estimation. Ruby Wu led the chassis and marker-holder CAD work; Sarah Zhong led the UDP communication implementation. We collaborated on software, electrical setup, and mechanical integration.','The system builds on Cornell course examples from Bruce Land and Van Hunter Adams, including VGA graphics, USB input, PWM, networking, and Protothreads. Low-level library adaptation and system integration were part of the work; these foundations were not written from scratch.']},
      {id:'architecture',title:'Two controllers, distinct responsibilities',paragraphs:['The interface controller handles mouse input, waypoint storage, route planning, and wireless transmission, with a dedicated core for rendering. The robot receives waypoints, reads BNO055 heading over I²C, and actuates its motors through PWM.','Semaphore signaling moves payload processing out of receive callbacks. Cooperative Protothreads organize concurrent firmware tasks without treating each task as a preemptive operating-system thread.'],bullets:['Interface: mouse → waypoint list → optional route ordering → UDP.','Robot: UDP → navigation state machine → PWM motor control.','Feedback: the BNO055 measures heading; traveled distance is estimated from time.']},
      {id:'decisions',title:'Separate the route from the controller',paragraphs:['Direct-follow mode preserves the input order. Optimized-route mode reorders the waypoint set using nearest-neighbor planning followed by 2-opt refinement. The latter targets a shorter route through the points; it does not preserve the original drawing’s stroke order or guarantee a globally shortest path.','Optimization is deferred until transmission and its result is cached. Adding waypoints invalidates the cached route. This keeps route computation out of the routine input/rendering path.','The robot uses heading feedback but has no wheel encoders. Forward travel duration is estimated from distance and expected speed, so orientation sensing does not provide closed-loop position control.']},
      {id:'validation',title:'Demonstration and its limits',paragraphs:['The public report and linked video document the integrated system. The report describes increased drawing drift when marker friction interferes with timed travel; it does not establish a quantitative position-accuracy bound.','A shorter commanded route and an accurately traced physical route are separate results. Surface conditions, wheel slip, and marker drag can change actual travel without being detected by the timing-based distance estimate.']},
      {id:'improvements',title:'Where the next iteration would focus',paragraphs:['The documented limitations point toward improving marker mounting and adding distance feedback. Those are potential improvements, not capabilities of the demonstrated car. A follow-up evaluation would need repeatable paths and position measurements to compare drawing accuracy across surface and marker conditions.']},
    ]
  },
  {
    slug:'gimbal-controller',title:'CUAir Gimbal Controller',shortTitle:'Gimbal Controller',summary:'A custom stabilization board connecting IMU sensing, C++ control firmware, servo actuation, and ground-station telemetry.',categories:['power-electronics','robotics-embedded'],featured:true,role:'Custom PCB, firmware, board bring-up, and integration',context:'Cornell CUAir',platform:'ATmega328P · Raspberry Pi telemetry bridge',status:'Board bring-up and integration',technologies:['Custom PCB','C++','PID control','I²C / UART'],media:'gimbal',caption:'Illustrative functional architecture based on the supplied project description; not a board layout or test capture.',links:[],sections:[
      {id:'problem',title:'Close the loop across hardware and firmware',paragraphs:['A gimbal controller links an orientation sensor to servo motion while exposing enough information to understand the system during integration. The work spans the custom electronics, embedded control loop, telemetry path, and physical interfaces.','This CUAir design uses an ATmega328P with an IMU, servo connections, UART, and programming and debug interfaces on a custom PCB.']},
      {id:'contribution',title:'My work: board through bring-up',paragraphs:['My work covered the custom stabilization PCB, C++ firmware, and board bring-up. Integration included power and interface debugging, with test points and LEDs providing access to the board’s behavior.','The controller is part of the CUAir system. Its electronics and firmware connect to servo hardware and the team’s ground-station telemetry path.']},
      {id:'architecture',title:'A control path and a visibility path',paragraphs:['IMU feedback reaches the ATmega328P over I²C. PID control in the firmware produces PWM servo commands. Angle telemetry leaves over UART and passes through a Raspberry Pi to the ground station.','These are complementary paths: the local feedback loop drives the gimbal, while the telemetry path exposes its reported angles during integration.'],bullets:['Sensor interface: I²C IMU feedback.','Control and output: C++ PID loop → PWM → servos.','Telemetry: UART → Raspberry Pi → ground station.','Bring-up access: programming connections, debug interfaces, test points, and LEDs.']},
      {id:'decisions',title:'Make integration observable',paragraphs:['The PCB includes test points and status LEDs alongside programming and debug interfaces. This gives bring-up work physical access to power and signals instead of relying only on the final mechanical behavior.','UART telemetry complements local board access by carrying angle information into the wider aircraft system. The architecture joins electrical design, control firmware, and system-level integration in one project.']}
    ]
  },
  {
    slug:'tinyrv2-processor',title:'TinyRV2 Five-Stage Pipelined Processor',shortTitle:'TinyRV2 Processor',summary:'A 27-instruction RISC-V subset in Verilog, explored through stalling and fully bypassed pipelines with latency-aware memory interfaces.',categories:['digital-design'],featured:false,role:'RTL implementation and processor verification',context:'Course processor-design project',platform:'Verilog · Python / pytest',status:'RTL implementation and simulation testing',technologies:['Verilog','RISC-V','Forwarding','pytest'],media:'pipeline',caption:'Illustrative five-stage pipeline. Forwarding and control relationships are explanatory, not captured simulation traces.',links:[],sections:[
      {id:'problem',title:'Preserve instruction behavior through a pipeline',paragraphs:['A pipeline overlaps instructions, but that overlap introduces dependencies: an instruction may need a result that has not yet been written back, a load may still be waiting for memory, and a branch may invalidate younger work.','The project implements a 27-instruction TinyRV2 RISC-V subset in Verilog, with stalling and fully bypassed five-stage variants. The design includes a variable-latency integer multiplier and valid/ready memory interfaces.']},
      {id:'contribution',title:'Implementation and verification scope',paragraphs:['The work described here covers datapath and control implementation, forwarding, interlocks, branch squashing, and verification using assembly tests and cycle-level traces. It is a course project; the ISA-model and test-infrastructure authorship is not attributed to me.']},
      {id:'architecture',title:'Five stages, explicit dependencies',paragraphs:['Fetch, decode, execute, memory, and writeback form the pipeline. Forwarding paths supply results from execute, memory, and writeback when they are available, reducing the need to wait for a register-file write.','A load-use dependency still needs a stall when the requested value is not yet available. Branch squashing removes younger instructions on a redirected path. The diagram abstracts these relationships and does not specify a measured stage timing.']},
      {id:'decisions',title:'Forward when possible; stall when necessary',paragraphs:['The stalling and bypassed variants expose two ways to preserve data dependencies. Forwarding needs source selection and dependency checks; stalling holds work until its inputs are available.','Valid/ready instruction and data memory interfaces make backpressure part of the control problem. A request or result cannot be treated as completed simply because a clock cycle has passed. The variable-latency multiplier introduces a similar need to account for completion.'],code:'// Illustrative dependency; not a captured test result\nlw  x1, 0(x2)\nadd x3, x1, x4\n\n// The add must wait until the loaded x1 is available.'},
      {id:'validation',title:'Check the ISA and inspect the cycles',paragraphs:['The verification approach uses directed and randomized assembly tests through Python/pytest, comparisons against a functional ISA model, and cycle-level traces. Functional comparison checks instruction-visible behavior; traces help explain where stalls, forwarding, and squashes occur.','No CPI, frequency, utilization, timing-closure, or coverage result is presented here. Simulation verification and FPGA implementation are distinct milestones.']},
      {id:'tinyrv1',title:'Companion: TinyRV1 on FPGA',paragraphs:['TinyRV1 is a separate eight-instruction, single-cycle processor, with a Verilog datapath and control and directed trace-based verification. This companion implementation was synthesized and deployed on an Intel Cyclone V FPGA.','The Cyclone V deployment belongs to TinyRV1. It is not evidence that the five-stage TinyRV2 processor was synthesized or deployed on that FPGA.']}
    ]
  },
  {
    slug:'avionics-power-converter',title:'12S → 24 V Avionics Power Converter',shortTitle:'Avionics Power Converter',summary:'A synchronous buck-converter design intended to power avionics from the primary flight battery, with protection, current sensing, and DroneCAN telemetry.',categories:['power-electronics'],featured:false,role:'Power-converter design and PCB layout',context:'Cornell CUAir avionics',platform:'Altium · DroneCAN · Pixhawk',status:'Converter design',technologies:['Altium','Synchronous buck','Current sensing','DroneCAN'],media:'power',caption:'Illustrative system architecture and design intent; not a released schematic or evidence of aircraft integration.',links:[],sections:[
      {id:'problem',title:'One flight battery, an avionics supply',paragraphs:['The design targets a 24 V avionics rail from a 12S primary flight battery. Its intended system benefit is to remove the need for a separate 6S avionics battery. This is the design objective, rather than a claim of demonstrated aircraft integration.','Power conversion is only one part of the system: protection, filtering, sensing, and telemetry connect the electrical supply to the aircraft’s avionics architecture.']},
      {id:'contribution',title:'My work: power electronics and layout',paragraphs:['The project covers synchronous buck-converter design and PCB layout in Altium, with transient protection, input filtering, input/output current sensing, and DroneCAN telemetry toward the Pixhawk and ground station.']},
      {id:'architecture',title:'Power path with a telemetry branch',paragraphs:['The power path runs from the primary battery through protection and filtering into the synchronous buck stage, then to the intended 24 V avionics load. Current sensing at the input and output provides visibility into the power path.','The telemetry branch carries information through DroneCAN to the Pixhawk and ground station. The diagram is a functional summary; it does not imply a particular protection component, switching frequency, or released board revision.']},
      {id:'decisions',title:'Treat the converter as part of the aircraft',paragraphs:['A synchronous buck topology provides the step-down conversion between the primary battery and the avionics rail. Input filtering and transient protection address the supply interface, while current sensing and DroneCAN address system visibility.','Altium design and layout bring those functions onto a PCB. The available description supports this architecture, but does not establish detailed placement choices, thermal behavior, or a completed bring-up sequence.']}
    ]
  },
  {
    slug:'galton-board',title:'Real-Time Galton Board',shortTitle:'Real-Time Galton Board',summary:'An RP2040 particle simulation that brings together fixed-point physics, multicore processing, and a PIO/DMA-driven VGA output path.',categories:['robotics-embedded'],featured:false,role:'Embedded C implementation and performance optimization',context:'Microcontroller simulation project',platform:'RP2040 · VGA',status:'Embedded implementation',technologies:['C','Fixed-point math','Multicore','PIO / DMA'],media:'galton',caption:'Illustrative compute-to-display data flow. This is not a simulation screenshot or a performance measurement.',links:[],sections:[
      {id:'problem',title:'Make a small processor do more work',paragraphs:['A Galton board simulation repeatedly updates moving particles and their collisions while producing a visible output. As the particle population grows, physics work competes with the constraints of a real-time display.','This RP2040 C implementation explores that boundary through multicore physics processing, fixed-point arithmetic, a distance approximation, and processor overclocking. VGA output uses PIO and DMA.']},
      {id:'contribution',title:'My work: implementation and optimization',paragraphs:['The work spans the embedded C simulation and its performance-oriented implementation: distributing physics work across cores, using fixed-point arithmetic, and applying the alpha-max-beta-min distance approximation. The display path uses the RP2040’s PIO and DMA peripherals.']},
      {id:'architecture',title:'Separate computation from signal generation',paragraphs:['Physics processing updates particle state, while the VGA path uses PIO and DMA for display output. Moving signal-generation work into peripherals changes how much CPU time is available for simulation.','Display refresh and physics update rate remain different quantities. A stable display signal alone does not establish that every particle has been updated within the same frame period.']},
      {id:'decisions',title:'Arithmetic, parallelism, and clock rate',paragraphs:['Fixed-point arithmetic changes the representation and cost of physics calculations. Alpha-max-beta-min approximates a distance using the larger and smaller absolute coordinate differences, avoiding an exact square root in that operation.','Multicore processing distributes physics work. Processor overclocking also contributes to the operating conditions, so any overall capacity improvement cannot be attributed entirely to software changes.'],bullets:['Arithmetic: fixed-point representation and approximate distance.','Concurrency: physics work distributed across cores.','Display: PIO and DMA for VGA output.','Operating conditions: processor clock changes are part of the performance story.']}
    ]
  }
];
export const categories = [
 {slug:'power-electronics',number:'01',title:'Power & Electronics',description:'Custom electronics for systems that have to work beyond the schematic. Power conversion, board bring-up, and avionics integration.',featured:'avionics-power-converter',diagram:'power'},
 {slug:'robotics-embedded',number:'02',title:'Robotics & Embedded',description:'Software with a physical output. Sensing, concurrent firmware, control, and performance on resource-constrained hardware.',featured:'autonomous-drawing-car',diagram:'gimbal'},
 {slug:'digital-design',number:'03',title:'Digital Design',description:'From an instruction to the hardware that executes it. Processor datapaths, pipeline control, verification, and FPGA implementation.',featured:'tinyrv2-processor',diagram:'pipeline'},
];
export function getProject(slug:string){return projects.find(p=>p.slug===slug)!}
